---
#ap-groups/vars/main.yml   

ap_groups_path: "{{role_path}}/ap_groups"

ap_groups:
  - name: CL17-Backoffice
    wlans: [CL17,  CL17-24, IPV6,  mgmt]
    rf_profile_a: Standard_a
    rf_profile_b: Standard_b
  - name: CL17-WOS
    wlans: [CL17,  IPV6,  mgmt]
    rf_profile_a: Standard_a
    rf_profile_b: None
  - name: CL17-General
    wlans: [CL17,  CL17-24, IPV6,  mgmt]
    rf_profile_a: Standard_a 
    rf_profile_b: Standard_b
  - name: CL17-Keynote
    wlans: [CL17,  IPV6,  mgmt]
    rf_profile_a: Keynote_a
    rf_profile_b: None
  - name: CL17-CAE
    wlans: [CL17, IPV6,  mgmt]
    rf_profile_a: Keynote_a
    rf_profile_b: None
  - name: CL17-DevNet
    wlans: [CL17,  IPV6, mgmt]
    rf_profile_a: Standard_a
    rf_profile_b: None
  - name: CL17-Keynote-demo
    wlans: [demo]
    rf_profile_a: Demo_a
    rf_profile_b: Demo_b

wlan_mapping:
    CL17: 
      wlan_id: 1
      if_name: customer_clients
    mgmt: 
      wlan_id: 22
      if_name: noc_clients
    IPV6:
      wlan_id: 4
      if_name: v6
    CL17-24:
      wlan_id: 21
      if_name: customer_clients
    demo:
      wlan_id: 23
      if_name: demo