---
#rf-profile/tasks/main.yml
- name: generate wlans config
  template: 
    src=ap_groups.j2
    dest="{{ap_groups_path}}/{{item.name}}_wlan"
  # loops over the rf_profiles defined in the vars folder
  with_items: "{{ wlans }}"
- name: assemble wlans config snippet in "{{config_snippets}}/wlans"
  assemble: 
    src="{{ap_groups_path}}"
    dest="{{config_snippets}}/ap_groups"
    regexp=".*_wlan"